FROM node:24-alpine AS builder
WORKDIR /workspace

RUN corepack enable && corepack prepare pnpm@latest --activate
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .
COPY . ./
RUN pnpm install --frozen-lockfile || true
RUN pnpm approve-builds --all
RUN pnpm install --frozen-lockfile
RUN pnpm build

FROM node:24-alpine AS runner
WORKDIR /workspace
RUN corepack enable && corepack prepare pnpm@latest --activate
COPY --from=builder /workspace/package.json /workspace/pnpm-lock.yaml /workspace/next.config.mjs /workspace/public ./
COPY --from=builder /workspace/.next ./.next
COPY --from=builder /workspace/node_modules ./node_modules
COPY --from=builder /workspace/src ./src

EXPOSE 3003
ENV NODE_ENV=production
CMD ["pnpm", "start"]
